### ISSUE TITLE
cannot use `get`

### ISSUE THREAD

**Issue by Kuangcp** [anapsix/docker-webdis#1]
i use httpie :
command:`http http://127.0.0.1:7379/GET/hello/`

result:`"ERR wrong number of arguments for 'get' command"`

also:
`curl http://127.0.0.1:7379/get/hello/`
{"get":[false,"ERR wrong number of arguments for 'get' command"]}

**Comment by anapsix** [comment]
@Kuangcp: try http://localhost:7379/get/hello
